yujin21.shin/220707_b11437.cpp

[트리] 11437 *

---

yujin21.shin/220713_b2206.cpp

BFS, visited(3차원), priority_queue

[BFS] 2206

---

yujin21.shin/220721_b2225.cpp

[DP] 2225*

---

jihun90.kim/220721_baekjoon2225.cpp

beakjoon2225 Update
- **참고 : 나머지의 합의 나머지는 합의 나머지와 같다.** (https://m.blog.naver.com/jacob7432/220628979099)

beakjoon2225

---

hyehyeon.kim/220728_baekjoon14002.cpp

14003 가장 긴 증가하는 부분 수열 5도 함께 통과할 수 있도록 DP 대신 이분 탐색을 사용한 코드입니다.

[22.07.28] 14002 가장 긴 증가하는 부분 수열 4

---

yujin21.shin/220728_b14002.cpp

[DP] 14002*

---

woori12.han/20220723_certi_pro.cpp
woori12.han/20220727_baek_14002.cpp

N(1 ~ 100000)명이 이사를 간다.
이사갈 거리가 가까운 순서대로 이사를 간다.
만약 거리가 같다면 이사갈 곳의 숫자가 큰 사람이 먼저 간다.
이사간 후 내 자리를 지나가는 사람에게는 사탕을 준다.
이사간 곳에 이미 사람이 앉아 있다면, 그 사람이 이사갈 때도 사탕을 준다.
input : 
1 //test case  수
9 // N
2 7 9 4 8 6 3 1 5 //이사가는 곳

[20220723 certi pro] 이사

---

aeri.youn/220811_backjoon2610.cpp

괴롭습니다.....unionfind랑 bfs했는데 28%에서 틀려요....

backjoon2610

---

hyehyeon.kim/220811_baekjoon2610.cpp

되는 대로 해서 코드가 지저분합니다.
대표자 구하고 오름차순 정렬하는 부분을 좀 더 깔끔하게 하고 싶지만 머리가 안돌아서 이만...

[22.08.11] 2610 회의준비

---

jihun90.kim/220811_baekjoon2610.cpp

도와주세요 여러분... 
반례 찾아보면 답은 전부 맞는데... 14퍼에서 틀려버립니다.. ㅠㅠ

baekjoon2610 미해결

---

woori12.han/20220810_baek_2610.cpp

2nd commit은 어디서 틀렸는지 모르겠.. 
floyd 를 꼭 써야하는걸까

2610 commit(fail)

---

woori12.han/20220824_baek_11779.cpp

11779 최소비용 구하기2

---

jihun90.kim/220823_baekjoon11779.cpp

baekjoon11778 미해결!

---

aeri.youn/220901_backjoon13334.cpp

[22.09.01] 철로 

---

jihun90.kim/220901_baekjoon13334.cpp

baekjoon13334 시간초과

---

aeri.youn/220915_backjoon1167.cpp

쩜쩜쩜
https://blog.myungwoo.kr/112

[22.09.15] 트리의 지름

---

woori12.han/20220915_baek_1167.cpp

1167 commit (fail)

---

hyehyeon.kim/221028_baekjoon14501.cpp

[22.10.28] 14501 퇴사

---

aeri.youn/221105_backjoon13460.cpp

참고 https://blog.naver.com/kbjid17/222562592503
너어무 어렵네여.............

backjoon 13460

---

hyehyeon.kim/221111_backjoon9251.cpp

[22.11.11] 9251 LCS

---

jihun90.kim/221118_baekjoon16947.cpp

beakjoon16947

---

aeri.youn/221202_backjoon1717.cpp

221202_backjoon1717

---

wonik.heo/220713_backjoon1717.cpp

1717번 집합의 표현

---

hyehyeon.kim/221202_backjoon1717.cpp

[22.12.02] 1107 집합의 표현

---

hyehyeon.kim/230106_backjoon17822.cpp

[23.01.06] 17822 원판 돌리기

---

hyehyeon.kim/230113_baekjoon2110.cpp

[23.01.13] 2110 공유기 설치

---

wonik.heo/220713_backjoon2110.cpp

2023 Week3 HomeWork

---

jihun90.kim/230203_baekjoon1162.cpp

다익스트라 함수 아웃풋 타입을 int로 줘서.. 삽질......... ㅠㅠㅠㅠㅠ

beakjoon1162

---

yujin21.shin/230203_b1162.cpp

[다익스트라-실패] 1162

---

jihun90.kim/230210_baekjoon3665.cpp

beakjoon3665.cpp

---

hyehyeon.kim/230210_baekjoon3665.cpp

[23.02.10] 3665 최종 순위

---

hyehyeon.kim/230217_baekjoon1520.cpp

[23.02.17] 1520 내리막 길

---

hyehyeon.kim/230224_baekjoon1949.cpp

[23.02.24] 1949 우수 마을

---

hyehyeon.kim/230228_baekjoon16566.cpp

set으로 풀면 개꿀아닌가 하고 덤볐는데 set::upper_bound는 매우 느리다는 것만 배우고 갑니다...

[23.03.03] 16566 카드 게임
